feat: add cypress against remote stack

diff --git a/.github/workflows/e2e-validation.yml b/.github/workflows/e2e-validation.yml
--- a/.github/workflows/e2e-validation.yml
+++ b/.github/workflows/e2e-validation.yml
@@ -18,6 +18,7 @@ on:
           - tools
           - production
           - perf
+          - ec2-node
 
 jobs:
   define-test-matrix:
@@ -29,21 +30,46 @@ jobs:
       - id: tests
         working-directory: app/web/cypress/e2e
         run: |
-            # get the names of all test subdirs with out slashes
-            test_dirs=$(find . -mindepth 1 -maxdepth 1 -type d  | sed 's|^\./||')
-            test_array="[]"
-            # put them into an array
-            for d in $test_dirs; do
-              test_array=$(echo "$test_array" | jq --arg d "$d" '. += [$d]')
-            done
-            test_array=$(echo "$test_array" | jq -c '.')
-            echo "$test_array"
-            echo "tests=$test_array" >> "$GITHUB_OUTPUT"
+          test_dirs=$(find . -mindepth 1 -maxdepth 1 -type d  | sed 's|^\./||')
+          test_array="[]"
+          for d in $test_dirs; do
+            test_array=$(echo "$test_array" | jq --arg d "$d" '. += [$d]')
+          done
+          test_array=$(echo "$test_array" | jq -c '.')
+          echo "$test_array"
+          echo "tests=$test_array" >> "$GITHUB_OUTPUT"
+
+  launch-ec2-node:
+    environment: ${{ inputs.environment }}
+    runs-on: ubuntu-latest
+    if: ${{ inputs.environment == 'ec2-node' }}
+    outputs:
+      remote-ip: ${{ steps.get-ip.outputs.remote_ip }}
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v4
+
+      - name: Deploy EC2 node
+        working-directory: .ci/
+        run: |
+          export SI_API_TOKEN="${{ secrets.SI_API_TOKEN }}"
+          export SI_WORKSPACE_ID="${{ vars.MANAGEMENT_WORKSPACE_ID }}"
+          python3 ./deploy-stack.py
+
+      - name: Save IP
+        id: get-ip
+        working-directory: .ci/
+        run: |
+          remote_ip=$(grep -Eo '([0-9]{1,3}\.){3}[0-9]{1,3}' ./ip)
+          echo "Remote IP set to ${remote_ip}"
+          echo "remote_ip=$remote_ip" >> "$GITHUB_OUTPUT"
 
   cypress-tests:
     environment: ${{ inputs.environment }}
     runs-on: ubuntu-latest
-    needs: define-test-matrix
+    needs: 
+      - define-test-matrix
+      - launch-ec2-node
     strategy:
       fail-fast: true
       matrix:
@@ -71,9 +97,67 @@ jobs:
           sudo apt update
           sudo apt install uuid -y
 
-      - name: Run Cypress Tests
+      - name: Setup SSH tunnel if ec2-node
+        if: ${{ inputs.environment == 'ec2-node' }}
+        working-directory: .ci/
         run: |
-          cd app/web
+          echo "$SSH_KEY" > ssh-key.pem
+          chmod 600 ssh-key.pem
+
+          remote_ip="${{ needs.launch-ec2-node.outputs.remote-ip }}"
+          echo "Tunneling EC2 node @ $remote_ip"
+
+          # Start SSH tunnel in background for 8080 (Web App) & 3020 (Bedrock)
+          nohup ssh -o StrictHostKeyChecking=no -L 8080:localhost:8080 arch@$remote_ip -i ssh-key.pem -N &
+          nohup ssh -o StrictHostKeyChecking=no -L 3020:localhost:3020 arch@$remote_ip -i ssh-key.pem -N &
+
+          # Wait for Bedrock (EC2 localhost:3020) to be ready
+          echo "Waiting for Bedrock to be ready..."
+          for i in {1..180}; do
+            if curl --fail --silent --max-time 2 http://localhost:3020/; then
+                echo "✅ Bedrock service is up and returned a valid response, preparing db"
+                curl --location 'http://localhost:3020/prepare' \
+                --header 'Content;' \
+                --header 'Content-Type: application/json' \
+                --data '{
+                  "recording_id": "W=01JYPR32SD5RKR3AMG298J7263-CS=01JZ3W5XX6QHQZ6PYSBHK4SB3K (39 components)",
+                  "parameters": {},
+                  "executionParameters": {}
+                }'
+                break
+            fi
+            echo "⏳ Attempt $i/180: Bedrock not responding yet. Retrying in 10s..."
+            sleep 10
+          done
+
+          # Fail if still not up after 30 min
+          if ! nc -z localhost 3020; then
+            echo "❌ Timed out waiting for bedrock service on port 3020"
+            exit 1
+          fi
+
+          # Wait for tunnel Web App (EC2 localhost:8080) to be ready
+          echo "Waiting up to 30 minutes for remote web app to be ready..."
+          for i in {1..180}; do
+            if curl --fail --silent --max-time 2 http://localhost:8080/health; then
+                echo "✅ Remote service is up and returned a valid response!"
+                break
+            fi
+            echo "⏳ Attempt $i/180: Service not responding yet. Retrying in 10s..."
+            sleep 10
+          done
+
+          # Fail if still not up after 30 min
+          if ! nc -z localhost 8080; then
+            echo "❌ Timed out waiting for web app on port 8080"
+            exit 1
+          fi
+        env:
+          SSH_KEY: ${{ secrets.SSH_KEY }}
+
+      - name: Run Cypress Tests
+        working-directory: app/web
+        run: |
           export VITE_AUTH0_USERNAME="${{ secrets.VITE_AUTH0_USERNAME }}"
           export VITE_AUTH0_PASSWORD="${{ secrets.VITE_AUTH0_PASSWORD }}"
           export VITE_SI_CYPRESS_MULTIPLIER="${{ vars.VITE_SI_CYPRESS_MULTIPLIER }}"
@@ -85,24 +169,16 @@ jobs:
           export VITE_AUTH_API_URL="https://auth-api.systeminit.com"
           export VITE_AUTH_PORTAL_URL="https://auth.systeminit.com"
 
-          # Retry loop with 3 attempts
           n=0
           max_retries=3
           
-          until [ $n -ge $max_retries ]
-          do
-
+          until [ $n -ge $max_retries ]; do
             unset exit_code || echo "exit_code not set"
-
-            # Run the npx task and store exit code in a variable
             npx cypress run --spec "cypress/e2e/${{ matrix.tests }}/**" || exit_code=$?
-
-            # Check the exit code
             if [ -z "$exit_code" ]; then
               echo "Cypress Test task succeeded!"
               break
             fi
-
             n=$((n+1))
             echo "Attempt $n/$max_retries failed with exit code $exit_code! Retrying..."
           done
@@ -136,16 +212,13 @@ jobs:
           path: artifacts
       - run: |     
           has_artifacts=false
-          # Check for marker files
           for marker in artifacts/*/*.mp4; do
             if [ -f "$marker" ]; then
               echo "Artifact detected for failed test: $marker"
-              echo "Setting failure to true and breaking"
               has_artifacts=true
               break
             fi
           done
-          # If at least one valid failure marker is present, then page
           if [ "$has_artifacts" = true ] && [ "${{ github.ref_name }}" = "main" ]; then
             curl --location "${{ secrets.FIREHYDRANT_WEBHOOK_URL }}" \
               --header "Content-Type: application/json" \
