Disable luminork tests due to flaking
Example: https://github.com/systeminit/si/actions/runs/16820701301

Signed-off-by: Nick Gerace <nick@systeminit.com>

diff --git a/.github/workflows/run-api-test.yml b/.github/workflows/run-api-test.yml
--- a/.github/workflows/run-api-test.yml
+++ b/.github/workflows/run-api-test.yml
@@ -144,61 +144,61 @@ jobs:
           name: ${{ matrix.tests.name }}
           path: artifacts/${{ matrix.tests.name }}
 
-  luminork-api-test:
-    name: API Test Luminork
-    environment: ${{ inputs.environment }}
-    runs-on: ubuntu-latest
-    env:
-      LUMINORK_API_URL: ${{ vars.LUMINORK_API_URL }}
-      LUMINORK_WORKSPACE_ID: ${{ vars.LUMINORK_WORKSPACE_ID }}
-      LUMINORK_AUTH_TOKEN: ${{ secrets.LUMINORK_AUTH_TOKEN }}
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v4
+  # luminork-api-test:
+  #   name: API Test Luminork
+  #   environment: ${{ inputs.environment }}
+  #   runs-on: ubuntu-latest
+  #   env:
+  #     LUMINORK_API_URL: ${{ vars.LUMINORK_API_URL }}
+  #     LUMINORK_WORKSPACE_ID: ${{ vars.LUMINORK_WORKSPACE_ID }}
+  #     LUMINORK_AUTH_TOKEN: ${{ secrets.LUMINORK_AUTH_TOKEN }}
+  #   steps:
+  #     - name: Checkout code
+  #       uses: actions/checkout@v4
 
-      - name: Install Deno
-        uses: denoland/setup-deno@v2
+  #     - name: Install Deno
+  #       uses: denoland/setup-deno@v2
 
-      - name: Run the deno exec with retry
-        run: |
-          cd bin/si-luminork-api-tests
-          ./scripts/run-tests.sh || exit_code=$?
+  #     - name: Run the deno exec with retry
+  #       run: |
+  #         cd bin/si-luminork-api-tests
+  #         ./scripts/run-tests.sh || exit_code=$?
 
-          # Check the exit code
-          if [ -z "$exit_code" ]; then
-            echo "Deno task succeeded [ or the orchestration failed for a totally non-valid reason ]!"
-            exit_code=0
-          else
-            echo "Luminork API tests failed"
-            cd ../..
-            mkdir -p artifacts/luminork_tests
-            echo "failure-marker" > artifacts/luminork_tests/failure-marker
-          fi
+  #         # Check the exit code
+  #         if [ -z "$exit_code" ]; then
+  #           echo "Deno task succeeded [ or the orchestration failed for a totally non-valid reason ]!"
+  #           exit_code=0
+  #         else
+  #           echo "Luminork API tests failed"
+  #           cd ../..
+  #           mkdir -p artifacts/luminork_tests
+  #           echo "failure-marker" > artifacts/luminork_tests/failure-marker
+  #         fi
 
-          echo "last_exit_code=$exit_code" >> "$GITHUB_ENV"
-          exit "$exit_code"
+  #         echo "last_exit_code=$exit_code" >> "$GITHUB_ENV"
+  #         exit "$exit_code"
 
-      - name: Upload artifact if exit code 53
-        if: failure()
-        run: |
-          if [ "${{ env.last_exit_code }}" == "53" ]; then
-            echo "Uploading marker for test luminork_tests"
-            mkdir -p artifacts/luminork_tests
-            echo "failure-marker" > artifacts/luminork_tests/failure-marker
-          fi
+  #     - name: Upload artifact if exit code 53
+  #       if: failure()
+  #       run: |
+  #         if [ "${{ env.last_exit_code }}" == "53" ]; then
+  #           echo "Uploading marker for test luminork_tests"
+  #           mkdir -p artifacts/luminork_tests
+  #           echo "failure-marker" > artifacts/luminork_tests/failure-marker
+  #         fi
 
-      - name: Upload artifacts
-        if: failure()
-        uses: actions/upload-artifact@v4
-        with:
-          name: luminork_tests
-          path: artifacts/luminork_tests
+  #     - name: Upload artifacts
+  #       if: failure()
+  #       uses: actions/upload-artifact@v4
+  #       with:
+  #         name: luminork_tests
+  #         path: artifacts/luminork_tests
 
   on-failure:
     runs-on: ubuntu-latest
     needs:
       - api-test
-      - luminork-api-test
+      # - luminork-api-test
     environment: ${{ inputs.environment }}
     if: failure()
     steps:
